Citizen.CreateThread(function()
	AddTextEntryByHash(GetHashKey("ghis2_bnt1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("ghis2_bnt2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("ghis2_bumr1"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("ghis2_skirt1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("ghis2_split1"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("ghis2_split2"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("ghis2_split3"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("ghis2_spoil_1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("ghis2_spoil_2"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("ghis2_spoil_3"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("ghis2_spoil_4"),"Tuning 11")
end)